<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose an optionRedWhiteBlack</name>
   <tag></tag>
   <elementGuidId>6e51e138-b7d4-48c9-bce7-3e2b7125da27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='color']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4b3ce812-f430-4456-9ca7-3b370690615c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>color</value>
      <webElementGuid>1620fb8c-a5a2-47c0-89ca-2b6926203ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_color</value>
      <webElementGuid>d94846ab-5c8b-4f8c-bbb0-540aa98adcb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_color</value>
      <webElementGuid>bd28a9a4-8542-4aec-9b40-28736a399d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>2447d68e-db3d-4d5f-9b01-4187e0821929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionRedWhiteBlack</value>
      <webElementGuid>8031fd10-8b4b-40cd-9e48-ec2cbb34675d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;color&quot;)</value>
      <webElementGuid>3fd51b0d-eed0-4dc2-b171-6929e665ffa9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='color']</value>
      <webElementGuid>587461ef-65fb-4790-8999-6ed5f637801a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-704']/div/div[2]/form/table/tbody/tr/td/select</value>
      <webElementGuid>d4cd9e1b-4dbb-45f2-a474-ca4e891676e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>6de03c95-9075-4650-ba32-1a8e6c8369be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size &amp; Fit'])[1]/following::select[1]</value>
      <webElementGuid>193616b5-d595-4ed3-851e-24274ec92c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/preceding::select[1]</value>
      <webElementGuid>4033abdf-a17e-4d6c-a93d-73d2762f28ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[2]</value>
      <webElementGuid>095340e8-f220-4420-be13-3bcd051c4536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>00ca4b73-7769-4b59-aed3-c2c3c848831b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'color' and @name = 'attribute_color' and (text() = 'Choose an optionRedWhiteBlack' or . = 'Choose an optionRedWhiteBlack')]</value>
      <webElementGuid>b6f61f1f-4238-48b5-99fe-bdf19a5f2072</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
