<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart(2)120.00</name>
   <tag></tag>
   <elementGuidId>c888cfe2-290d-454f-b2cd-9b4155becf83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cart-name-and-total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-cart']/a/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cbd9fc4a-4798-40a5-927a-63c213ff1200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-name-and-total</value>
      <webElementGuid>d8a275b5-28dc-4fc3-a22a-488dedaf3b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart(2)₹120.00</value>
      <webElementGuid>3daffa4f-24aa-47a0-8358-d8a9145d6de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-cart&quot;)/a[@class=&quot;cart-button&quot;]/span[@class=&quot;cart-item has-items&quot;]/span[@class=&quot;cart-name-and-total&quot;]</value>
      <webElementGuid>8a9120d2-f638-4ba6-9000-a76f9def8ee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-cart']/a/span/span[2]</value>
      <webElementGuid>0f02590e-6099-48f6-afe6-a878b8543ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::span[3]</value>
      <webElementGuid>7b0f9d48-04f5-4b86-82fe-cdbcce96355a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::span[3]</value>
      <webElementGuid>b2f5f1d8-d8bb-4022-b4e2-697756079e5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Black Cross Back Maxi ...'])[1]/preceding::span[3]</value>
      <webElementGuid>1b1ac875-25ef-41d7-a5c2-d57399870623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cart(2)']/parent::*</value>
      <webElementGuid>fb2b131f-ae14-4c7c-9e2e-6302b0642a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>06f63a5a-0d8e-49c8-af61-4b100176db4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cart(2)₹120.00' or . = 'Cart(2)₹120.00')]</value>
      <webElementGuid>cac7964b-0ab3-4e86-9bff-9903deac9be7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
