<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cart(4)155.00</name>
   <tag></tag>
   <elementGuidId>9ad7a705-dda9-420f-a0bc-c040dfd58560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cart-name-and-total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-cart']/a/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6d36ee4a-7094-48e5-8d41-9c6f67c59e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-name-and-total</value>
      <webElementGuid>cfff3d6a-c66c-4733-b454-548668090991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cart(4)₹155.00</value>
      <webElementGuid>39f2a027-de40-4fe0-87de-31982b749d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-cart&quot;)/a[@class=&quot;cart-button&quot;]/span[@class=&quot;cart-item has-items&quot;]/span[@class=&quot;cart-name-and-total&quot;]</value>
      <webElementGuid>080faa1e-5e72-48dd-9e24-eb4eb0eaca1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-cart']/a/span/span[2]</value>
      <webElementGuid>92eeed56-96a4-4bba-ac96-e8bcf1e0366f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::span[3]</value>
      <webElementGuid>1addde1d-59cb-4f2e-913d-4f55b70a0f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/following::span[3]</value>
      <webElementGuid>b7cd8874-3dda-4dc6-a069-e586c47307a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pink drop shoulder ove...'])[1]/preceding::span[3]</value>
      <webElementGuid>71782fca-500b-4288-8d04-4c5b6f7d6c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cart(4)']/parent::*</value>
      <webElementGuid>b9416f39-4b27-44a5-9a71-8a10d4a3f98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>669c6b28-1dfc-4b4c-aa5e-983ab3819a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Cart(4)₹155.00' or . = 'Cart(4)₹155.00')]</value>
      <webElementGuid>579d54ea-ff29-4b23-b808-366af473226e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
