<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Place order</name>
   <tag></tag>
   <elementGuidId>89ca3386-b7af-4961-9060-59ba8f982540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#place_order</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='place_order']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3a932e39-e989-414a-8697-62e48bbfd257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c5515db8-b947-4b6e-90ba-1abf21c39807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button alt</value>
      <webElementGuid>0ceb0da8-606b-4880-967d-987ac6896479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>woocommerce_checkout_place_order</value>
      <webElementGuid>a3f97da7-8d81-41ab-969d-bffab55ce019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>place_order</value>
      <webElementGuid>8e922e82-a495-47c1-9a7c-e01629c97427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>df663d5c-fcaf-4600-ad9e-b57de01670ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>4c187f5e-45ed-4579-94ea-fbc43be8d114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>036927e6-60be-4df3-846e-cbd8dfd6cb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;place_order&quot;)</value>
      <webElementGuid>c2c5dd18-07a4-4e26-972a-6df85831c89f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='place_order']</value>
      <webElementGuid>9857d3a4-dd58-45cb-9043-44b4303d5cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/button</value>
      <webElementGuid>ee52a7e3-e3fd-47ab-806e-631f881ad5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::button[1]</value>
      <webElementGuid>16633588-ae15-4922-b1a3-7d1351c28e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='terms and conditions'])[1]/following::button[1]</value>
      <webElementGuid>6b024539-bf22-4bfa-be01-3e344c7d2d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='opening time'])[1]/preceding::button[1]</value>
      <webElementGuid>8ddf240a-ea75-42c1-b33a-f0c63f421d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon - Fri: 8AM - 10PM'])[1]/preceding::button[1]</value>
      <webElementGuid>cfbd0986-35e4-435b-b144-6cc94d8c3cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Place order']/parent::*</value>
      <webElementGuid>c4e610b8-f67b-42b2-a616-3ea5e29aabb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/button</value>
      <webElementGuid>da7dd117-681c-4c16-a8d7-18e276d837b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'woocommerce_checkout_place_order' and @id = 'place_order' and (text() = 'Place order' or . = 'Place order')]</value>
      <webElementGuid>a314ec6c-5eb0-4ca3-8613-7888720f2595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
