<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__billing_postcode</name>
   <tag></tag>
   <elementGuidId>79ae4a34-bc3b-4e8e-b3cf-6cd7358576a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dff7b47-3585-40c2-8bc5-dfe476e3fdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8c146a9-4440-4004-9bfb-ba6fff1b033a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>50e13bbb-d677-4248-9836-fc20a99d82f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>9304addb-308f-4e0c-970f-495057d6995c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_postcode</value>
      <webElementGuid>bf46a8de-dbcb-4ea4-b7e0-4fe8159312a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>postal-code</value>
      <webElementGuid>a7a652fc-b26d-4f30-b4d6-3840a34c551c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_postcode&quot;)</value>
      <webElementGuid>0b3dcf59-bcb1-44b4-8e3d-ca9b5d85ebc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_postcode']</value>
      <webElementGuid>4c079943-7997-4abe-abf2-797fd1f8383c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_postcode_field']/span/input</value>
      <webElementGuid>27d0fd54-10c3-4e59-90bc-ae06ee27ad55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[9]/span/input</value>
      <webElementGuid>8261e706-fec9-46f6-a075-ea4b36438c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_postcode' and @id = 'billing_postcode']</value>
      <webElementGuid>e8ed5256-2d3c-4d78-a3d6-38f7bde9d38d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
