<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(optional)_billing_company (1)</name>
   <tag></tag>
   <elementGuidId>6b702a9d-8cc5-465d-b819-d315b413199d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_company</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_company']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b61c406-5ea2-4111-a1b3-b449f3be1384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e7a919a-4ce2-4aa3-b585-77865120e10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>106f3444-666a-49cd-a742-f00f392e5eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>9bf9e0f6-52f1-4cbd-a44d-df46ce6ab7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_company</value>
      <webElementGuid>eede0f94-1755-4720-984f-edf8e9e432d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>juaracoding</value>
      <webElementGuid>acb67d40-a8f6-4cee-ab23-db99b09bb6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>organization</value>
      <webElementGuid>f6ca0d3a-0c67-4450-a99c-cb168a5eecf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_company&quot;)</value>
      <webElementGuid>8cea3bf2-fe6f-4444-a35f-b5e84a92c671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_company']</value>
      <webElementGuid>8884aeda-4d68-4ed3-80a6-3d694a2ccd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_company_field']/span/input</value>
      <webElementGuid>93a45e44-0e72-4d0d-9029-11b0836af204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/span/input</value>
      <webElementGuid>6d9c5c38-df32-4180-ac1f-6ae676939cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_company' and @id = 'billing_company']</value>
      <webElementGuid>88db4b92-581e-4af5-8198-05ed64be861e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
