<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Phone</name>
   <tag></tag>
   <elementGuidId>f7d3be7d-795d-493a-b52e-1920f1f1b566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_phone_field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='billing_phone_field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>03540bcd-d82c-46c5-9057-da9658110320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-row form-row-wide validate-required validate-phone</value>
      <webElementGuid>d40a92de-d6f9-46a0-a1bd-1abd6099f073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_phone_field</value>
      <webElementGuid>2c8304c4-779f-4a7e-9da9-b99b8de3ed17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-priority</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b8af505e-16cf-4fc6-a3e2-191af9f1ea76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone *</value>
      <webElementGuid>706c32a2-9885-4412-8365-01491da411a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_phone_field&quot;)</value>
      <webElementGuid>511e471e-4823-4408-b344-28541933a4ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='billing_phone_field']</value>
      <webElementGuid>e50622e4-1afd-4c52-9c3f-682127fc9d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_details']/div/div/p[10]</value>
      <webElementGuid>f285b4ad-2265-42ff-b23e-8dae73738037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::p[1]</value>
      <webElementGuid>6a16076e-b27a-47e9-ba6a-d33841f84cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]</value>
      <webElementGuid>18b16309-1463-435d-9e61-fc93806431bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'billing_phone_field' and (text() = 'Phone *' or . = 'Phone *')]</value>
      <webElementGuid>d95b6fc7-e58d-4130-b768-981444dcc80e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
