<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_(optional)_order_comments</name>
   <tag></tag>
   <elementGuidId>1e22d234-5350-43f1-af54-ce8e5237e744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#order_comments</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='order_comments']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e3198612-3f04-4089-a15f-2200cd7846bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>b4d5e110-9aad-461d-99b8-764470f4a2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>b28851dc-21c2-4a96-a8bb-310136c79e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_comments</value>
      <webElementGuid>e9d38509-8cde-4e32-88f7-3db9f1a1b405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes about your order, e.g. special notes for delivery.</value>
      <webElementGuid>68fd442e-b9a6-4d82-9935-63ee72c1fda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>34bdd003-5303-471f-b90f-e00a6f4db77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>539f0e7a-0165-4b19-bd88-e69a51d6563f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_comments&quot;)</value>
      <webElementGuid>af893a5d-6b0a-48d5-b778-0600b113f5a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='order_comments']</value>
      <webElementGuid>4371eaba-0388-418e-a465-c35e0e81e96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='order_comments_field']/span/textarea</value>
      <webElementGuid>31fcb7ab-fcd9-43c9-b934-0cf69171eeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>157aa627-5439-44f3-b1c6-87549d830be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'order_comments' and @id = 'order_comments' and @placeholder = 'Notes about your order, e.g. special notes for delivery.']</value>
      <webElementGuid>749dc11c-9b81-4d66-87ed-dc178063d419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
