<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Type and Press Enter to Search_s</name>
   <tag></tag>
   <elementGuidId>bc086876-7d99-4456-9eba-8e804e40d024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;s&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='s']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>751f57f6-b9db-407b-bafd-036a2aa231b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>07b7bd59-f54a-4a42-af7d-166590f29584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>039022ca-b696-48a7-8948-1c0127c9ac19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3adea4ed-d86c-4e18-9105-226035329800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noo-site&quot;)/header[@class=&quot;noo-header fixed_top header-3 header-eff&quot;]/div[@class=&quot;search-header search-header-eff&quot;]/div[@class=&quot;noo-container&quot;]/form[@class=&quot;form-horizontal noo-mebla-searchform&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>85fb0212-887b-48b3-abd2-59e2de01487a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='s']</value>
      <webElementGuid>6c41768b-74ec-4b28-955a-5a1a3f54a8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noo-site']/header/div[3]/div[2]/form/input</value>
      <webElementGuid>784df7e8-7209-4bed-ab40-646e1872234a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4aa16ece-c5c5-45ba-9d6b-3871d9fafe9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 's']</value>
      <webElementGuid>d4d1f9bb-1124-4da2-bc85-f3527b7c7ba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
