<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rememberme (1)</name>
   <tag></tag>
   <elementGuidId>63974bac-a447-405c-8e96-86556ffe3f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rememberme</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rememberme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e69f5395-08a0-40c5-93f3-3dd57c26788b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-form__input woocommerce-form__input-checkbox</value>
      <webElementGuid>09b1e66c-7d30-42aa-a6d8-57503ac98465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rememberme</value>
      <webElementGuid>7c43a1b7-9374-4459-90be-06f81caa2e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f7f50dcd-cd2e-4cf1-ade3-83479b77e9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberme</value>
      <webElementGuid>9af1d59e-eee7-4c1b-afcd-80240426b3da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>forever</value>
      <webElementGuid>94b9c86d-c80f-4288-a78f-328aa040c3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rememberme&quot;)</value>
      <webElementGuid>4c833ba2-fec8-402e-b43a-fa7de25a547b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rememberme']</value>
      <webElementGuid>e0e88a33-bb13-47ab-9550-bc17b801a433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer_login']/div/form/p[3]/label/input</value>
      <webElementGuid>0e1efd16-c80d-4552-9b0d-593d6f8cf642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>01d3bf58-005a-4c59-8c69-3629bc779ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rememberme' and @type = 'checkbox' and @id = 'rememberme']</value>
      <webElementGuid>46ad13e1-9d95-41b3-ab0c-7fee04cf05db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
